### ISSUE TITLE
Abos missverständlich/falsch

### ISSUE THREAD

**Issue by thoschneider** [wi-wissen/instahub-doc-de#10]
Hallo,

jede Person im Netzwerk hat unter ihrem Usernamen die Zähler "Photos", "Abonnenten" und "abonniert". Drückt man auf "abonniert", so steht dort z.B. "Personen die adrian211 folgen". Es muss dort aber heißen "Personen, DENEN adrian211 folgt" !

Drückt man auf "Abonnenten" so steht dort "Abonnenten von adrian211". Das ist missverständlich/unklar: Könnte beides heißen, nämlich Personen, denen Adrian folgt oder Personen, die Adrian folgen. Besser wäre die letztere Formulierung, also "Personen, die adrian211 folgen".

Gruß

Thomas

**Comment by wi-wissen** [comment]
Das Problem wird mit dem nächsten Release angegangen: https://github.com/wi-wissen/InstaHub/commit/8093b4a4d477b88207fcd2ab1a1d23e41527a472 - hier wird der dein erster Absatz behoben. Der zweite sollte damit eindeutig sein.

Die Beta ist schon jetzt auf https://instahub.yak9.de/ Sobald ich selbst oder mit Unterstützung ausreichend getestet habe, kann ich diese Version produktiv nehmen.

**Comment by wi-wissen** [comment]
Änderungen sind produktiv.
