### ISSUE TITLE
Aufgabenstellung unklar

### ISSUE THREAD

**Issue by wunderlich** [wi-wissen/instahub-doc-de#11]
Die folgende Aufgabenstellung ist nicht ganz klar:

https://github.com/wi-wissen/instahub-doc-de/blob/cedbc03c7eb4e51c14b1f0c5952d7ce82a27307c/exercices.md?plain=1#L452

Ich vermute, du meinst eher

```
Wer hat in Kommentaren zu Fotos Adolf Hitler erwähnt? Gib deren Email und den betreffenden Kommentar aus.
```

**Comment by wi-wissen** [comment]
Danke für den Hinweis. Kommt am 25. Februar mit der neuen InstaHub-Version und damit überarbeiteten Dokumentation.
