### ISSUE TITLE
Kardinalität der Beziehung "has" zwischen photos und tags

### ISSUE THREAD

**Issue by ghost** [wi-wissen/instahub-doc-de#12]
Hallo :-)

nach meinem Verständnis dürfte die Relation "has" zwischen den Entitätstypen photos und tags eine n:m-Beziehung sein, oder? Die Namen sind ja schließlich keine Primärschlüssel. Das ER-Modell in der Dokumentation suggeriert, dass jeder (Hash-)Tag nur für ein Bild genutzt werden könne (siehe hier: https://wi-wissen.github.io/instahub-doc-de/#/erm?id=erm-f%c3%bcr-den-betrieb-des-sozialen-netzwerks). 

Lg

EDIT: Gerade noch entdeckt: "comments" ist auch eine n:m-Beziehung, keine n:n-Relation.

**Comment by wi-wissen** [comment]
`comments` ist in der Tat so wie du schreibst.

`tags` ist aber genauso umgesetzt, wie es beschrieben ist. Natürlich würde man es als n:m implementieren, aber das hatte ich damals, wo ich gestartet bin nicht gemacht. Jetzt lassen sich Modelländerungen quasi nicht mehr umsetzen ohne das Risikoe bestehende Hubs zu zerstören.
